```{r}
library(tidyverse)
library(ggplot2)
library(Seurat)
library(colorrepel)
```

```{r}
a <- readRDS("umap_gg.rds")
b <- a + scale_color_manual(values = color_repel(a, sim = colorspace::tritan, severity = 0.5, verbose = T))
c <- gg_color_repel(a, verbose = T, seed = 34, nsamp = 1000, out_worst = T)
cowplot::plot_grid(a, b, c,
  labels = c("original", "color_repel", "worst")
)
# ggsave("scRNAseqUMAP_example.png", width = 7, height = 3)
```

```{r}
a <- readRDS("vln_gg.rds")
b <- a + scale_fill_manual(values = color_repel(a, sim = colorspace::tritan, col = "fill"))
cowplot::plot_grid(a, b,
  labels = c("original", "color_repel")
)

profvis::profvis(gg_color_repel(a))
# ggsave("scRNAseqVln_example.png", width = 7, height = 3)
```

```{r}
library(ggplot2)
a <- ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = as.factor(cyl))) +
  theme_classic()
b <- a + scale_color_manual(values = color_repel(a, sim = colorspace::tritan, verbose = T))
c <- gg_color_repel(col = "colour")
cowplot::plot_grid(a, b, c,
  labels = c("original", "color_repel")
)
```

```{r}
a <- readRDS("bar_gg.rds")
b <- a + scale_fill_viridis_d(option = "H")
c <- b + scale_fill_manual(values = color_repel(b, col = "fill"))
c <- gg_color_repel(b, col = "fill", verbose = T, seed = 45, sim = colorspace::deutan)
cowplot::plot_grid(a, b, c, labels = c("default", "viridis", "color_repel"), nrow = 1)
# ggsave("stackbar_example.png", width = 18, height = 4)
```

```{r}
so <- readRDS("/gpfs/internal/analysis/NYGC/Project_NYGC_15254_B01_NAN_Lane/compbio/results/mouse/sobjs/so.rds")
# saveRDS(g, "spatialdim_gg.rds")
g <- Seurat::DimPlot(so)
Idents(so) <- "Spatial_snn_res.0.8"
g <- Seurat::SpatialDimPlot(so, images = "slice1", image.alpha = 0)
g2 <- gg_color_repel(g, col = "colour", verbose = T, sim = colorspace::deutan, autoswitch = TRUE)
cowplot::plot_grid(g, g2, labels = c("default", "color_repel"), nrow = 1)
# ggsave("spatialdim_example.png", width = 8, height = 4)

profvis::profvis(g2 <- gg_color_repel(g, col = "colour", verbose = T, sim = colorspace::deutan, autoswitch = TRUE))
```

```{r}
a <- readRDS("umap_gg.rds")
b <- gg_color_repel(a, verbose = T)
c <- gg_color_repel(b, verbose = T)
```
# trace clusters

```{r}
g2 <- a
em <- dplyr::select(g2$data, 1, 2)
ems <- split(em, g2$data$shortread_type)
dat <- map(1:length(ems), function(x) {
  em1 <- ems[[x]]
  distm1 <- distances::distances(em1)
  distm1 <- as.matrix(distm1)
  cut1 <- quantile(unlist(distm1), probs = 0.1)
  n1 <- colSums(distm1 <= cut1)
  sel1 <- n1 >= nrow(em1)/30
  dat1 <- em1[sel1,] %>% mutate(shortread_type = names(ems)[x])
}) %>% bind_rows()
# em1 <- ems[[1]]
# distm1 <- distances::distances(em1)
# distm1 <- as.matrix(distm1)
# cut1 <- quantile(unlist(distm1), probs = 0.05)
# n1 <- colSums(distm1 <= cut1)
# sel1 <- n1 >= 7 & n1 <= 20
# dat1 <- em1[sel1,]
g3 <- gg_color_repel(g2) + ggalt::geom_encircle(data = dat, expand = 0.02, s_shape = 0.5, alpha = 0.2, aes(x = UMAP_1, y = UMAP_2, fill = shortread_type), show.legend = F)
# plotly::ggplotly(g3)
ggsave("example_geom_encircle.pdf", g3, width = 5, height = 5)

gg_color_repel(a, encircle = T)
```


